name: "Update Banner"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - uses: actions/setup-node@master
        with:
          node-version: 20

      - name: Run Script
        run: npm run start

      - name: push banner.png to the images branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: images
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}